default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { '127.0.0.1' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3333 } %>

development:
  <<: *default
  database: test

# test:
#   <<: *default
#   database: member_management_test


# production:
#   <<: *default
#   database: member_management_production
#   username: member_management
#   password: <%= ENV['MEMBER_MANAGEMENT_DATABASE_PASSWORD'] %>
